# Generated by Django 3.1.6 on 2021-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
