# Generated by Django 3.1.6 on 2021-02-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_voucher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
